# VeriChainX Railway Configuration for Hackathon
version: 2

services:
  verichainx-api:
    source: .
    build:
      buildCommand: pip install -r requirements.txt
      startCommand: uvicorn main_tidb:app --host 0.0.0.0 --port $PORT
    healthcheck:
      path: /health
      interval: 30
      timeout: 10
    env:
      PYTHONUNBUFFERED: "1"
      PORT: "8000"
    resources:
      memory: 512MB
      cpu: 0.25