# VeriChainX Render Configuration for Hackathon
services:
  - type: web
    name: verichainx-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main_tidb:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
    plan: free
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1